import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';

export const lightTheme = {
  ...MD3LightTheme,
  dark: false,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#002E62',
    onPrimary: '#ffffff',
    primaryContainer: '#dbeafe',
    onPrimaryContainer: '#002E62',
    secondary: '#3C8DBC',
    onSecondary: '#ffffff',
    secondaryContainer: '#e0f2fe',
    onSecondaryContainer: '#0369a1',
    background: '#f8fafc',
    onBackground: '#0f172a',
    surface: '#ffffff',
    onSurface: '#0f172a',
    surfaceVariant: '#f1f5f9',
    onSurfaceVariant: '#475569',
    outline: '#cbd5e1',
    outlineVariant: '#e2e8f0',
    error: '#dc2626',
    onError: '#ffffff',
    elevation: {
      ...MD3LightTheme.colors.elevation,
      level1: '#ffffff',
      level2: '#f8fafc',
      level3: '#f1f5f9',
    },
  },
  custom: {
    cardBackground: '#ffffff',
    cardBorder: '#e2e8f0',
    mutedText: '#64748b',
    headerTitle: '#002E62',
    inputBackground: '#f8fafc',
    inputBorder: '#cbd5e1',
    logoBg: '#f8fafc',
    qrButtonBg: '#f1f5f9',
    divider: '#e2e8f0',
    shadowColor: '#002E62',
  },
};

export const darkTheme = {
  ...MD3DarkTheme,
  dark: true,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#38bdf8',
    onPrimary: '#0f172a',
    primaryContainer: '#1e3a8a',
    onPrimaryContainer: '#bae6fd',
    secondary: '#60a5fa',
    onSecondary: '#0f172a',
    secondaryContainer: '#1e293b',
    onSecondaryContainer: '#93c5fd',
    background: '#0b132b',
    onBackground: '#f8fafc',
    surface: '#1c2541',
    onSurface: '#f8fafc',
    surfaceVariant: '#243052',
    onSurfaceVariant: '#94a3b8',
    outline: '#3a506b',
    outlineVariant: '#243052',
    error: '#f87171',
    onError: '#0f172a',
    elevation: {
      ...MD3DarkTheme.colors.elevation,
      level1: '#1c2541',
      level2: '#243052',
      level3: '#3a506b',
    },
  },
  custom: {
    cardBackground: '#1c2541',
    cardBorder: '#3a506b',
    mutedText: '#94a3b8',
    headerTitle: '#38bdf8',
    inputBackground: '#0b132b',
    inputBorder: '#3a506b',
    logoBg: '#243052',
    qrButtonBg: '#243052',
    divider: '#3a506b',
    shadowColor: '#000000',
  },
};

export type AppTheme = typeof lightTheme;
